# Generated by Django 2.2.17 on 2020-11-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='situacao',
            field=models.CharField(default='ativo', max_length=7),
            preserve_default=False,
        ),
    ]
